#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x330239C1C4DAFEE1 (classic@zzzcomputing.com)
#
Name     : deprecated-Mako
Version  : 1.0.7
Release  : 51
URL      : http://pypi.debian.net/Mako/Mako-1.0.7.tar.gz
Source0  : http://pypi.debian.net/Mako/Mako-1.0.7.tar.gz
Source99 : http://pypi.debian.net/Mako/Mako-1.0.7.tar.gz.asc
Summary  : A super-fast templating language that borrows the  best ideas from the existing templating languages.
Group    : Development/Tools
License  : MIT
Requires: deprecated-Mako-bin = %{version}-%{release}
Requires: deprecated-Mako-license = %{version}-%{release}
Requires: deprecated-Mako-python = %{version}-%{release}
Requires: MarkupSafe
BuildRequires : MarkupSafe
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : funcsigs
BuildRequires : nose
BuildRequires : python-core
BuildRequires : python-mock
BuildRequires : setuptools-legacypython
BuildRequires : six

%description
=========================
Mako Templates for Python
=========================
Mako is a template library written in Python. It provides a familiar, non-XML
syntax which compiles into Python modules for maximum performance. Mako's
syntax and API borrows from the best ideas of many others, including Django
templates, Cheetah, Myghty, and Genshi. Conceptually, Mako is an embedded
Python (i.e. Python Server Page) language, which refines the familiar ideas
of componentized layout and inheritance to produce one of the most
straightforward and flexible models available, while also maintaining close
ties to Python calling and scoping semantics.

%package bin
Summary: bin components for the deprecated-Mako package.
Group: Binaries
Requires: deprecated-Mako-license = %{version}-%{release}

%description bin
bin components for the deprecated-Mako package.


%package legacypython
Summary: legacypython components for the deprecated-Mako package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-Mako package.


%package license
Summary: license components for the deprecated-Mako package.
Group: Default

%description license
license components for the deprecated-Mako package.


%package python
Summary: python components for the deprecated-Mako package.
Group: Default
Provides: deprecated-mako-python

%description python
python components for the deprecated-Mako package.


%prep
%setup -q -n Mako-1.0.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554341456
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-Mako
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-Mako/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/mako-render

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-Mako/LICENSE

%files python
%defattr(-,root,root,-)
